name: Build and push Rust service Docker images
on:
  push:
    paths:
    - 'crates/**'
    - '.dockerignore'
    - '.github/workflows/rust.yml'
    - '.github/workflows/rust-docker.yml'
    - 'ci/Dockerfile.rust'
    - 'ci/rust-docker-target.sh'
    - 'Cargo.toml'
    - 'Cargo.lock'
    - 'flake.nix'
    - 'flake.lock'

jobs:
  build:
    name: 'rust docker build'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    #if: github.repository == 'PluralKit/PluralKit'
    steps:
      - run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - if: github.event_name != 'pull_request' && ${{ !env.ACT }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: nix build .#docker-gateway
      - run: ./result | docker load
      - if: github.event_name != 'pull_request'
        run: |
          docker tag pluralkit-gateway:latest ghcr.io/asleepyskye/pluralkit-gateway:latest
          docker push ghcr.io/asleepyskye/pluralkit-gateway:latest
          docker tag pluralkit-gateway:latest ghcr.io/asleepyskye/pluralkit-gateway:${{ github.sha }}
          docker push ghcr.io/asleepyskye/pluralkit-gateway:${{ github.sha }}