name: Build and push Rust service Docker images
on:
  push:
    paths:
    - 'crates/**'
    - '.dockerignore'
    - '.github/workflows/rust.yml'
    - '.github/workflows/rust-docker.yml'
    - 'ci/Dockerfile.rust'
    - 'ci/rust-docker-target.sh'
    - 'Cargo.toml'
    - 'Cargo.lock'
    - 'flake.nix'
    - 'flake.lock'

jobs:
  build:
    name: 'rust docker build'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        service: 
          - gateway
          - api
          - migrate
          - dispatch
          - avatars
          - scheduled_tasks
          - gdpr_worker
    
    #if: github.repository == 'PluralKit/PluralKit'
    steps:
      - run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v15
        with:
          name: asleepyskye-pluralkit-testing
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - if: github.event_name != 'pull_request' && ${{ !env.ACT }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: nix build .#docker-${{ matrix.service }}
      - run: ./result | docker load
      - if: github.event_name != 'pull_request'
        run: |
          IMAGE_NAME="${{ github.repository_owner }}/pluralkit-${{ matrix.service }}"
          IMAGE_ID=$(echo "ghcr.io/$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')

          docker tag pluralkit-${{ matrix.service }}:latest $IMAGE_ID:latest
          docker push $IMAGE_ID:latest

          docker tag pluralkit-${{ matrix.service }}:latest $IMAGE_ID:${{ github.sha }}
          docker push $IMAGE_ID:${{ github.sha }}